name: Build and Push Docker Image # 워크플로우 이름

on:
  push:               # 코드가 GitHub에 업로드(push)될 때 실행됩니다.
    branches:
      - main          # main 브랜치에서만 실행되도록 설정합니다.

jobs:
  build:
    runs-on: ubuntu-latest # 최신 우분투 환경에서 작업을 실행합니다.
    env:                   # 환경 변수 설정
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub 사용자 이름을 환경 변수에 저장
    steps:
      # 1. GitHub 저장소에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Docker Hub에 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # GitHub Secrets에 저장된 Docker Hub 사용자명
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # GitHub Secrets에 저장된 Docker Hub 비밀번호

      # 3. Docker 이미지 생성
      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/file_board_frontend_image:latest .

      # 4. Docker Hub에 이미지 업로드
      - name: Push Docker image
        run: docker push $DOCKERHUB_USERNAME/file_board_frontend_image:latest


        
